### ISSUE TITLE
Not working for qBittorrent v4.5.2 Web UI (64-bit)

### ISSUE THREAD

**Issue by EnduringGuerila** [Carve/qbittorrent-webui-cjratliff.com#70] opened 2024-09-29 06:44 UTC
![image](https://github.com/user-attachments/assets/814cb459-ce56-4e5b-a1ac-a82ab18763ec)
Just cloned and this is what mine looks like.

DarkReader usually does a decent job but has occasional issues, and I tried to embed qbit in nextcloud which lead me to wanting an official dark theme again. (picture is with DarkReader fully disabled)

It's hosted in a debian lxc with nothing else running.

**Comment by Carve** [comment] 2024-09-29 12:39
Clear your browser cache completely (sometimes completely closing the browser after helps too) and it will be shown as intended.

**Closed as completed** 2024-09-30 12:55 UTC
